---
title: "Activity: simulation"
format: html
editor: source
---

**Instructions:** 

* Work with a neighbor to answer the following questions 
* To get started, download the [class activity template](https://sta279-f25.github.io/class_activities/ca_12_template.qmd) file
* When you are finished, render the file as an HTML and submit the HTML to Canvas (let me know if you encounter any problems)

## Probability simulation: the birthday problem

Suppose we have a class of 30 students. What is the probability that there is at least one shared birthday?

* Assume there are 365 days in a year
* Assume that each day is equally likely as a birthday
* Assume there are no multiple-birth siblings (e.g. twins, triplets, etc.) in the class

1. Create a vector to store the days of the year (numbered 1 to 365)

2. Use the `sample` function to randomly choose birthdays for the class (think about whether we want to sample with or without replacement here...)

3. Check the number of distinct birthdays (hints: `unique` returns the unique elements of a vector; `length` returns the length of a vector). Are there 30 distinct birthdays?

4. Use a for loop to repeat the experiment `nsim=10000` times, making sure to store the results. What is the probability of at least one shared birthday?

5. How many students do we need for the probability to be approximately 50%?
