---
title: "Activity: Data wrangling in Python"
format: html
editor: source
---

**Instructions:** 

* Work with a neighbor to answer the following questions 
* You do not need to submit anything for this activity

**Working in Python:** To work in Python, you will connect to the DEAC OnDemand server:

[https://sta279-f25.github.io/resources/rstudio_server/](https://sta279-f25.github.io/resources/rstudio_server/)

# Overview

## Back to the Gapminder data

In this activity, we will revisit the Gapminder data that we have worked with previously. To load the Gapminder data into Python, run the following code in R:

```{r, message=F, warning=F}
library(gapminder)
```

Then run the following code in Python:

```{python, message=F, warning=F}
import pandas as pd
import numpy as np

gapminder = r.gapminder
```

Use Python and pandas to complete the following questions.

1. Choose only the rows in the gapminder data for countries in Asia in 2002.

2. Count the number of countries in each continent for the data in 2002. (*hint*: use the `'count'` function in `agg`)

3. Use the `assign` function to create a new column which contains the natural log of GDP per capita. (You may need to look up pandas documentation for the `assign` function).

4. Create the following table:

```{python, echo=F, message=F, warning=F}
(gapminder.assign(log_gdp = np.log(gapminder['gdpPercap']))
  .query('year == 2002')
  .groupby(by = 'continent', observed=True)
  .agg(num_countries = ('country', 'count'), mean_log_gdp = ('log_gdp', 'mean'))
)
```