---
title: "Does interacting with dogs help relieve exam stress?"
format: html
editor: source
---

# Background

With the goal of helping students manage stress, many colleges and universities provide the opportunity for students to interact with animals (dogs, goats, rabbits, etc), particularly during final exam season. While these sessions are often popular, however, we may wonder whether they do really help reduce feelings of stress.

To investigate this question, a 2022 paper analyzed the results of an experiment in which students interacted with dogs, and reported their feelings of stress before and after the interaction. Students were randomly assigned to one of three groups with different levels of dog interaction, and the researchers hypothesized that students who interacted directly with a dog would benefit more.

# The data

To download the data, run the following chunk of code in R:

```{r, message=F, warning=F}
library(readr)

raw_data <- read_csv("https://sta279-f25.github.io/class_activities/canine_raw.csv")
```

Each row of the data represents one student who particpated in the study. You will notice that there are many columns (210, in fact!). Several columns give some information about the student in the experiment (their age, their year in school, etc.). The remainder of the columns record measurements of the participant's well-being and ill-being before and after the intervention.

## Variables

**Demographic variables:**

* `Age_Yrs`: the student's age in years
* `Year_of_Study`: The participants year in college. First (1), second (1), third (3), fourth (4), fifth or more (5).
* `Live_Pets`: Pets back home (1), or no pets back home (2).
* `Consumer_BARK`: Low (1), medium (2), or high (3) consumer of the BARK program

**Study variables:**

* `GroupAssignment`: the treatment group to which the student was randomly assigned: Control (the student did not interact with a dog), Indirect (a dog was present but the student didn't pet them), and Direct (a dog was present and the student could interact directly with the dog)
* `PN1_*`: Positive and negative affect item responses on the pre-test. There are 10 positive/negative affect items. Pre-test positive affect scores can be calculated from `PN1_3`, `PN1_5`, `PN1_7`, `PN1_8`, `PN1_10`. Pre-test negative affect scores can be calculated from `PN1_1`, `PN1_2`, `PN1_4`, `PN1_6`, `PN1_9`.
* `PN2_*`: Positive and negative affect item responses on the post-test. There are 10 positive/negative affect items. Post-test positive affect scores can be calculated from `PN2_3`, `PN2_5`, `PN2_7`, `PN2_8`, `PN2_10`. Post-test negative affect scores can be calculated from `PN2_1`, `PN2_2`, `PN2_4`, `PN2_6`, `PN2_9`.
* `HA1_*`: Happiness item responses on the pre-test. There are 4 happiness items.
* `HA2_*`: Happiness item responses on the post-test. There are 4 happiness items.
* `F1_*`: Flourishing scale item responses on the pre-test. There are 8 flourishing items. 
* `F2_*`: Flourishing scale item responses on the post-test. There are 8 flourishing items.
* `SC1_*`: Social connectedness scale item responses on the pre-test. There are 20 social connectedness items.
* `SC2_*`: Social connectedness scale item responses on the post-test. There are 20 social connectedness items.
* `S1_1`: Stress scale response on the pre-test. Only one item is used to measure stress.
* `S2_1`: Stress scale response on the post-test. Only one item is used to measure stress.
* `HO1_1`: Homesickness scale response on the pre-test. Only one item is used to
measure homesickness.
* `HO2_1`: Homesickness scale response on the post-test. Only one item is used to measure homesickness.
* `HO1_2`: Integration scale response on the pre-test. Only one item is used to measure integration
* `HO2_2`: Integration scale response on the post-test. Only one item is used to measure
integration.
* `L1_*`: Loneliness scale item responses on the pre-test. There are 20 loneliness items.
* `L2_*`: Loneliness scale item responses on the post-test. There are 20 loneliness items.

# Research question

The researchers hypothesize that interacting with a dog (directly or indirectly) results in higher measures of well-being and lower measures of ill-being compared to the handler-only treatment.

How would you use the available data to answer this research question? Describe any data cleaning, visualization, statistical modeling, and hypothesis testing needed.


